source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'Thematic_Example' do
  pod 'Thematic', :path => '../'

  target 'Thematic_Tests' do
    inherit! :search_paths

    
  end
end
